version: '3.4'


services:
  nginx:
    image: nginx:1.13
    container_name: eth_ec_server.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./eth_ec_server/static:/static
    depends_on:
      - web

  db:
    image: mysql:5.7
    container_name: eth_ec_server.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: eth_ec_serverpass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: ./web
    container_name: eth_ec_server.web
    command: >
      bash -c "uwsgi --socket :8001 --module eth_ec_server.wsgi
      && npm run dev
      && python manage.py collectstatic
      && python manage.py migrate
      && python manage.py loaddata eth_ec_server/ec_site/fixtures/ec_seed.json
      && python manage.py loaddata eth_ec_server/ec_site/fixtures/ec_seed2.json
      && python manage.py loaddata eth_ec_server/ec_site/fixtures/ec_seed3.json
      && python manage.py loaddata eth_ec_server/ec_site/fixtures/ec_seed4.json"
    volumes:
      - ./eth_ec_server:/code
      - ./eth_ec_server/static:/static
    expose:
      - "8001"
    depends_on:
      - db
