# Generated by Django 2.1.7 on 2019-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0002_user_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.FloatField(),
        ),
    ]
